package:
  name: oommf
  version: "2.0a0_20170929a0"  # [unix]
  version: "2.0a0_20170929a0"  # [win]

# On Windows, we install from precompiled binary packages.
# On Unix, we build from source.
source:
   url: https://github.com/fangohr/oommf/archive/2.0a0_20170929a0.tar.gz  # [unix]
   url: https://math.nist.gov/oommf/dist/oommf20a0_20170929_86_x64.zip    # [win]
   sha256: 3439d1c9e95cc7395bc2e2330bba8cf198585d1b350251ea8561c1554ff8c7fd  # [unix]
   sha256: 71d5fdc958b7e582e90e9da8a50f9b1a8f224dc731bb8aab381484186213b54e  # [win]

build:
  number: 2
  skip: True  # [win32]

requirements:
  build:
    - toolchain  # [unix]
    - tk 8.5*  # [unix]
    - tk 8.6*  # [win]
    - curl  # [win]
    - 7za  # [win]
  run:
    - tk 8.5*  # [unix]
    - tk 8.6*  # [win]

test:  # [unix]
  commands:  # [unix]
    - oommf +version  # [unix]

about:
  home: http://math.nist.gov/oommf/
  license_file: oommf/LICENSE  # [unix]
  license_file: LICENSE  # [win]
  license: Custom
  summary: 'Object Oriented MicroMagnetic Framework (OOMMF)'

  description: |
    The Object Oriented MicroMagnetic Framework (OOMMF) forms a
    completely functional micromagnetics package. OOMMF is written in
    C++. For portable user interfaces, it uses Tcl/Tk so that OOMMF
    operates across a wide range of Unix, Windows, and MacOSX
    platforms.

    The recipe for building OOMMF conda package was developed by
    Thomas Kluyver, Ryan A. Pepper, Marijan Beg, and Hans Fangohr
    at the University of Southampton and European XFEL GmbH as a part of
    OpenDreamKit – Horizon 2020 European Research Infrastructure project (676541).

    This conda package version contains Dzyaloshinskii-Moriya extensions,  # [unix]
    for crystallographic classes Cnv, T(O), and D2d, which  # [unix]
    which are not included in the OOMMF binaries and tarballs from NIST.  # [unix]
    For details about these extensions please visit https://github.com/fangohr/oommf.git.  # [unix]

  doc_url: http://math.nist.gov/oommf/doc/

extra:
  recipe-maintainers:
    - fangohr
    - marijanbeg
    - takluyver
    - davidcortesortuno
    - rpep
