appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: ToRdvj9m3/wtPowW4um/R1/3jG9/9XbIUovSgWA9t1Mxfrp9h1vfT9PO/V9lMXsn9HLDQ/GaoSPN5D1HphpC9KIz/Pxv5yMN/toF+bOH4OdozhydL/E5in1edLg+tTARXDNUgw4ylc148HepFSk0JFomie8qbWBZKk9vFtcnUZRfNkzdG9LMBrczxHhGLyMYBx91lYdQF+OZi+MNqtUHl3e/Ndh+ChZ7Su5IzuWPCbdBa8rJS7NE/IjzNHF0RzCAFYS1Z7JsZTZS+zAqgFZbefbeXA3N0MmR5lwiLXEOCG+EbOjHGbl8VssjcaXSGGUwOJx0E+LD9hAnvjR2tfSOe0pWsjJR81hSJZdswdzyDacTpE2Ai9Czs7zszXvZyPX9Dea9R/N5KghxyoedjJGGJ4cHPPopGBqTu6F8+w6jOY9VBe2eJ8x9+KvHp1pRupsAfgOeWenyjDeUSn6MUg5ywMqe94+diY3W5VsuqcGcNhfoBko7saMF5qFlIpX8h41LSl1/7t9BnJ1l8WU8wFEuUbQKIPDA0nux6T5JDRUpOWk7SxSwUkZ1dxcoUohEzIqh9XBLXHD7lLMHOL0tBq+xExoNgNry0jse065ge/LPAqX69g2ETBamXuUeeeoXw1MZE/AnbEbBQ4xexyaqEpC1tFhkOjd0ip96BsA1cBSc4nU=}
provider:
  win: azure
conda_forge_output_validation: true
