travis:
  secure:
    BINSTAR_TOKEN: F1LXxm/3ehnXIAT7qLHLyzq3KDQ41kEJp8wjZ6vlmYttlKkQr9Y8sgIF9DPBhuNXm+wnKcX0DBdHGB4qd979qtYKWBIsICTu0QyFljrsFLSlssPLJQpJ0/u4v338IxeHayZ5t81nDBRjhdpMoD6sC5Jg/ZHT3UZR4Jrxpos1WzKwtAKQX64F3kmZMLRZOx3lJzh3qSNuqIooczE/S838O/50LboQzTmrreCrq2uic9ObZ8Kt3Gium0fXNM8vzpDhYfZfSozKe+FPEM30payTgS/FqkJO45+FnNva9HOG2DOAwqfIEtiihY0Yw4wWZzhfLdM7LHtX6hw+kCqn7OW+33kV+sYDpEfjxr8gV2nxVHopRrGjTgDL1NBOwzt+hyw7f6dRIlT1OxSNSn6XFAnfZKQJRsPpNaZjgNSZtYq5S4Od/3uiZv7QEinhxrJtPFUuxpkh40lVrJlnYI8jyM4+K6/+st/l90feFlj6gCs6nT3tl6vG5YKnHpmNXTcMP8OOt7mx21o90ay2VjNeZowVMQmK5nYYkjYMCDvKNjz7BBLLZiyDAHQ/8EW8wG4N3mBb5jgy1s3KCRrd+OIUVbbakWW/fo4j4EAmhKBrlg2pISKuWhQHdDe4+gsPgBeuPud4GAQ4b/Q8HDpeKHh50mLyEuLmqhK8YViWSdlat3W5oFM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
