travis:
  secure:
    BINSTAR_TOKEN: iye8rHPhmGEluhE/SRrp6Ooy6IR8V0Wm0xjo0j/huFGswx+u7Dgwtwa8de3w5IzQi7XaWdsZ850AsJsSKf/cN68/jxCwXwqYNILwicvrtC2V6R1yDeH67VOKBMv7i6TsOH2THt//etp928A6evlskxhckzAlbq50vA7l9406FF+vNGduT92zqzzOFq06hVh0g/IE694FWEEGzmmhysHyd6a+cSJmoLdxiyrVrscjbj7EGLCgfT086tIz7g9MkzE0YTbifAZUCf/iSdTjt/JKA611flmPRmmu8LV8bv8mSQuQUEyRe9io/J6aydVUhD6PsycT9XlFoM49HwU7A17yAX2feABqrgrPM0suE9Mo0vuLixvHts5x3Wngzn7Y8YXKih/AscbTTJCXM1dk/AYxEabCMrXIZ2OBmAfTnF7/dVocMiikX3sV9/AE/pR7oI71vM6XXOB6Gfxv5xwuMXoy0EQioqwl8c/6KJFd04yoKk8n6SclqomkZpOYaJxkUSTzUz0vkLVKoVUXAxIEk7J4pcMOnYJ4tEZ0OpqCsLNVjzaB0czJrAW9lcvvEAuMfXUB+JOEhApZERaA/Ndu8hve17GwffVNujCR3/67M9hhyJg9Jj9qozT+01Q9TyudI9VJrPWbcvo71i5HaH98M0mX6SKpHgORU0wXNfIWO9DMr04=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
